# -*- coding: utf-8 -*-
"""Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nPeZap7KaFNI5FXsCfxPOKKnQlVuk4O
"""

for i in range(1,6):
    print(i)

for i in range(1,11):
    if i%2==1:
        print(i)

for i in range(3):
    for j in range(2):
      print(i,j)

for i in range(1,8):
    if i==5:
        break
    print(i)